Repository anshjindal/tdp-tender-discovery-platform, pull requests merged in 2025-04, with the labels that each got.

#104 Task-id [86a7m0v35]
  cicd/team_tdp_206/Dockerfile.frontend
  cicd/team_tdp_206/Jenkinsfile
  cicd/team_tdp_206/k8s/backend-deployment.yaml
  cicd/team_tdp_206/k8s/frontend-deployment.yaml
  package-lock.json
  package.json
Labels: TDP206

#110 [Deveops#3] Docker Integration
  .dockerignore
  apps/backend/Dockerfile.backend
  apps/frontend/Dockerfile.frontend
  docker-compose.yml
Labels: TDP202

#108 CU-86a7jm1nv - Format Data Output
  apps/frontend/src/features/tdp-ca/pages/ca-main.tsx
Labels: TDP203

#109 CU-86a7g7k57 - Docker Integration & Image Management
  cicd/team_tdp_203/Dockerfile.backend
  cicd/team_tdp_203/Dockerfile.frontend
  cicd/team_tdp_203/Jenkinsfile
Labels: TDP203

#111 Mahmoud's changes
  apps/frontend/src/features/tdp-lg/pages/TenderData.tsx
  apps/frontend/src/features/tdp-tm/pages/MyBids.tsx
Labels: TDP207

#70 add docker build and push stages to jenkinsfile for backend service
  apps/backend/package.json
  apps/frontend/src/features/tdp-kb/components/SearchBar.tsx
  apps/frontend/src/features/tdp-kb/pages/kb-main.tsx
  apps/frontend/src/features/tdp-lg/pages/TenderSearch.tsx
  cicd/tdp205/.dockerignore
  cicd/tdp205/Dockerfile.backend
  cicd/tdp205/Dockerfile.frontend
  cicd/tdp205/Jenkinsfile
  package-lock.json
  package.json
Labels: TDP205
