Repository anshjindal/tdp-tender-discovery-platform, pull requests merged in 2025-03, with the labels that each got.

#72 206- rateLimiter backend
  apps/backend/src/middleware/rateLimiter.ts
Labels: TDP206

#73 206 rateLimiter integration
  apps/backend/src/main.ts
Labels: TDP206

#75 [86a7hpraw] Add ArticleCard component for Knowledge Base Module
  apps/frontend/src/features/tdp-kb/components/ArticleCard.tsx
  apps/frontend/src/features/tdp-kb/pages/kb-main.tsx
Labels: TDP205

#66 86a7jjg88: Added use states to keep track of editable fields in profile settings
  apps/backend/src/services/userServices.ts
  apps/frontend/src/components/layouts/Sidebar.tsx
Labels: TDP206

#61 206 Cancel changes update
  apps/frontend/src/components/layouts/Sidebar.tsx
Labels: TDP206

#86 Add keyword-based capability assessment logic to backend
  apps/rfp_backend/rfp_backend/main.py
Labels: TDP203

#89 CU-86a7k6r1c - Fixed Routing to CA
  apps/frontend/src/routes/AppRoutes.tsx
Labels: TDP203

#90 Feat 86a7jm1ry: Add Loading Spinners
  apps/frontend/src/features/tdp-ca/components/FileList.tsx
  apps/frontend/src/features/tdp-ca/components/LoadingSpinner.tsx
  apps/frontend/src/features/tdp-ca/hooks/useFileUpload.ts
  apps/frontend/src/features/tdp-ca/pages/UploadDoc.tsx
  apps/frontend/src/styles/styles.css
  apps/frontend/src/utils/axios.customize.ts
Labels: TDP203

#81 TDP 207: Improved responsive UI for tender search page Task ID: 86a7hm9j2
  apps/frontend/src/features/tdp-lg/pages/TenderSearch.tsx
Labels: TDP207

#85 Feat_tdp_204_definebroadcat_86a7htv9u
  apps/frontend/src/features/tdp-bm/pages/ContactGrouping.tsx
  apps/frontend/src/features/tdp-bm/pages/bm-main.tsx
  cicd/team_204/Jenkinsfile
  cicd/team_204/k8s/frontend-service.yaml
Labels: TDP204

#80 86a7k4kf5: Error fixing from latest merge
  apps/backend/src/main.ts
  apps/frontend/src/components/layouts/Sidebar.tsx
Labels: TDP206

#82 Feat tdp 205
  apps/frontend/src/features/tdp-lg/pages/TenderSearch.tsx
Labels: TDP205

#83 feat(86a7g7kxc): CI/CD setup
  cicd/TDP207/Dockerfile.backend
  cicd/TDP207/Dockerfile.frontend
  cicd/TDP207/Jenkinsfile
  cicd/TDP207/k8s/backend-deployment.yaml
  cicd/TDP207/k8s/backend-service.yaml
  cicd/TDP207/k8s/frontend-deployment.yaml
  cicd/TDP207/k8s/frontend-service.yaml
  cicd/TDP207/k8s/ingress.yaml
Labels: TDP207

#88 Clickup Task: #86a7hmtxm | Fix and update the My Tenders Dashboard to be responsive
  apps/frontend/src/components/BidDashboard.tsx
  apps/frontend/src/components/SubmittedTenderDetails.tsx
  apps/frontend/src/components/TenderList.tsx
  apps/frontend/src/features/tdp-tm/pages/TenderDashboard.tsx
Labels: TDP207

#78 Implemented ArticleList component for Knowledge Base
  apps/frontend/src/features/tdp-kb/components/ArticleCard.tsx
  apps/frontend/src/features/tdp-kb/components/ArticleList.tsx
  apps/frontend/src/features/tdp-kb/pages/kb-main.tsx
Labels: TDP205

#102 86a7h98nx - Implemented functionality to allow users to save changes
  apps/frontend/src/components/layouts/Sidebar.tsx
Labels: TDP206
